output_format: "json"
output_directory: "output"

sites:
  - name: grailed
    enabled: true
  - name: depop
    enabled: true
  - name: stockx
    enabled: false
  - name: goat
    enabled: false

count: 30

subtemplates:
  depop: depop_subtemplate.html.j2
  grailed: grailed_subtemplate.html.j2